---
title: "Lab 00 - Hello IDS!"
author: "Ethan Li"
date: "`r Sys.Date()`"
output: html_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
```

### Exercises 16-17

We set up the data frame. Edit the data below to include information about your team members.

```{r setup-tibble}
team_data <- tibble(
  name = c("Seors", "Shane", "Adam", 
           "Yusuf", "Roan", "Ethan"),
  github_username = c("se0rs", "shanewright01", "Mispell", 
                      "username 3", "roanhowie", "ipenvaer"), 
  colour = c("red", "black", "blue", 
             "black", "blue", "red"),
  hobby = c("golf", "gym", "badminton", 
            "piano", "walk", "football"),
  favourite_number = c(3, 7, 7, 5, 9, 8)
  )

team_data
```

### Exercise 18

We now work on visualising our data. 

```{r bar-plot}
p1 <- ggplot(data = team_data, 
             mapping = aes(x = github_username, 
                           y = favourite_number,
                           fill = colour), 
             ) +
   geom_col() +
   scale_fill_identity()
p1
```

*Remove this text (including the stars), and add your answer for Exercise 18 here.*

